[tool.flet]
app_title = "Calcio Premium"
bundle_id = "com.tuonome.calciopremium"

[tool.flet.android]
permissions = ["INTERNET", "ACCESS_NETWORK_STATE"]
# Questo assicura che il video possa essere lanciato all'esterno
manage_external_storage = false
